// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmYfbkeQBP0lo7qPx64vBHD4gZZUrgkXM',
    appId: '1:683493018296:web:b0b69a260393ee37afc24d',
    messagingSenderId: '683493018296',
    projectId: 'todoapp-8696a',
    authDomain: 'todoapp-8696a.firebaseapp.com',
    storageBucket: 'todoapp-8696a.firebasestorage.app',
    measurementId: 'G-NJQ85M08XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYPzU1VtGux5oA0g3s_ghpPD4CIopFKw',
    appId: '1:683493018296:android:f894ee243f69c4f1afc24d',
    messagingSenderId: '683493018296',
    projectId: 'todoapp-8696a',
    storageBucket: 'todoapp-8696a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3AAn5c5s3iYgf2RpMK1ZGJQsbXMFQLiY',
    appId: '1:683493018296:ios:82d1a1f60b244988afc24d',
    messagingSenderId: '683493018296',
    projectId: 'todoapp-8696a',
    storageBucket: 'todoapp-8696a.firebasestorage.app',
    iosBundleId: 'com.example.reelView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3AAn5c5s3iYgf2RpMK1ZGJQsbXMFQLiY',
    appId: '1:683493018296:ios:82d1a1f60b244988afc24d',
    messagingSenderId: '683493018296',
    projectId: 'todoapp-8696a',
    storageBucket: 'todoapp-8696a.firebasestorage.app',
    iosBundleId: 'com.example.reelView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmYfbkeQBP0lo7qPx64vBHD4gZZUrgkXM',
    appId: '1:683493018296:web:242c9aeeec653e37afc24d',
    messagingSenderId: '683493018296',
    projectId: 'todoapp-8696a',
    authDomain: 'todoapp-8696a.firebaseapp.com',
    storageBucket: 'todoapp-8696a.firebasestorage.app',
    measurementId: 'G-5YRHELCB4Z',
  );
}
